global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pharma-compliance'
    static_configs:
      - targets: ['pharma-compliance:8083']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
