global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'grid-balancing'
    static_configs:
      - targets: ['grid-demo:8082']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
