apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-os.fullname" . }}-audit-collector
  labels:
    {{- include "agent-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit-collector
spec:
  type: {{ .Values.auditCollector.service.type }}
  ports:
    - port: {{ .Values.auditCollector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agent-os.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: audit-collector
