global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'defi-sentinel'
    static_configs:
      - targets: ['defi-sentinel:8081']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
